trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: container
  steps:
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: $(dockerserviceconnection)
    displayName: Login to dockerhub
  - script: |
      docker build -t ukhydrographicoffice/azdo-build-exporter .
    displayName: 'Build exporter and image'
  - script: |
      docker push ukhydrographicoffice/azdo-build-exporter
    displayName: 'Push image'
- job: exporterexe
  pool:
    vmImage: 'windows-latest'
  container: golang:latest
  steps:
  - script: |
      go get
      go build .
  - publish: $(Build.SourcesDirectory)/*.exe
    artifact: executable
