trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(dockerserviceconnection)
  displayName: Login to dockerhub
- script: |
    docker build -t ukhydrographicoffice/azdobuildexporter .
  displayName: 'Build exporter and image'
- script: |
    docker push ukhydrographicoffice/azdobuildexporter
  displayName: 'Push image'

